version: '3'
services:
  back:
    build:
      context: .
      dockerfile: ./container/dockerfile/Dockerfile.dev
    environment:
      NODE_ENV: $NODE_ENV
      DATABASE_URL: ${SQLITE_DATABASE_URL}
    volumes:
      - sqlite_data:/app/data
    networks:
      - private-network
    ports:
      - 3000:3000

networks:
  private-network:
    driver: bridge

volumes:
  sqlite_data:
    drive: local